FROM tensorflow/tensorflow:latest-gpu-py3
LABEL maintainer="shgupta@pivotal.io"

WORKDIR /usr/src/app

COPY ["parse_cfenv.py", "requirements-gpu.txt", "neural_style.py", "neural_style_server.py", "nst_utils.py", "tensorflow_demo.py", "./"]
COPY ["./output/", "./output/"]
COPY ["./tfadain/", "./tfadain/"]

RUN apt-get update && apt-get install -y python3-tk && pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements-gpu.txt

ENV rabbitmq.username='guest' rabbitmq.password='guest' rabbitmq.server='rabbitmq' rabbitmq.port='5672' rabbitmq.vhost='/' profile='local'

CMD ["python", "neural_style_server.py"]