---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-web-deployment
  labels:
    app: flask-web

spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-web
  template:
    metadata:
      labels:
        app: flask-web
    spec:
      containers:
      - name: web-server
        image: shagupta/flask-web-server:latest
        tty: true
        ports:
        - containerPort: 8080
        env:
        - name: rabbitmq.password
          value: "guest"
        - name: rabbitmq.username
          value: "guest"
        - name: rabbitmq.server
          value: "rabbitmq.default.svc.cluster.local"
        - name: rabbitmq.port
          value: "5672"
        - name: rabbitmq.vhost
          value: "/"
        - name: profile
          value: "local"

