---
apiVersion: v1
kind: Pod
metadata:
  name: flask-fib-server
  labels:
    app: flask-fib

spec:
  containers:
  - name: flask-fib-server
    image: shagupta/flask-web-server:latest
    tty: true
    imagePullPolicy: Always
    env:
    - name: rabbitmq.password
      value: "guest"
    - name: rabbitmq.username
      value: "guest"
    - name: rabbitmq.server
      value: "rabbitmq.default.svc.cluster.local"
    - name: rabbitmq.port
      value: "5672"
    - name: rabbitmq.vhost
      value: "/"
    - name: profile
      value: "local"
    command: ["python3"]
    args: ["rpc_server.py"]

